version: "3"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "6060:6060"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app

  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - backend-network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarqube-db:
    image: postgres:alpine
    networks:
      - backend-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_db: {}
