version: "3"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "6060:6060"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app

  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "90:90"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: {}
